extensions:
    pim-attribute-edit-form-identifier:
        module: pim/common/simple-view
        config:
            template: pim/template/common/drop-zone

    pim-attribute-edit-form-identifier-validation-params:
        module: pim/common/simple-view
        parent: pim-attribute-edit-form-identifier
        targetZone: content
        position: 100
        config:
            template: pim/template/form/tab/section
            templateParams:
                sectionTitle: pim_enrich.form.attribute.tab.properties.validation
                dropZone: content

    pim-attribute-edit-form-identifier-validation-params-max-characters:
        module: pim/attribute-edit-form/properties/text
        parent: pim-attribute-edit-form-identifier-validation-params
        targetZone: content
        position: 100
        config:
            fieldName: max_characters

    pim-attribute-edit-form-identifier-validation-params-validation-rule:
        module: pim/attribute-edit-form/properties/select
        parent: pim-attribute-edit-form-identifier-validation-params
        targetZone: content
        position: 110
        config:
            fieldName: validation_rule
            choices:
                regexp: pim_enrich.entity.attribute.validation_rule.regexp

    pim-attribute-edit-form-identifier-validation-params-validation-regexp:
        module: pim/attribute-edit-form/properties/validation-regexp
        parent: pim-attribute-edit-form-identifier-validation-params
        targetZone: content
        position: 120
        config:
            fieldName: validation_regexp
