extensions:
    pim-attribute-edit-form:
        module: pim/attribute-edit-form

    pim-attribute-edit-form-cache-invalidator:
        module: pim/cache-invalidator
        parent: pim-attribute-edit-form
        position: 1000

    pim-attribute-edit-form-form-tabs:
        module: pim/form/common/form-tabs
        parent: pim-attribute-edit-form
        targetZone: content
        position: 100

    pim-attribute-edit-form-properties:
        module: pim/common/tab/properties
        parent: pim-attribute-edit-form-form-tabs
        targetZone: container
        position: 100
        config:
            label: pim_enrich.form.attribute.tab.properties.title

    pim-attribute-edit-form-properties-common:
        module: pim/attribute-edit-form/properties/common
        parent: pim-attribute-edit-form-properties
        targetZone: accordion
        position: 100
        config:
            mode: create

    pim-attribute-edit-form-properties-type-specific:
        module: pim/attribute-edit-form/type-specific-form
        parent: pim-attribute-edit-form-properties
        targetZone: accordion
        position: 110
