pim_enrich_attribute_remove:
    path: /{id}/remove
    defaults: { _controller: pim_enrich.controller.attribute:removeAction }
    requirements:
        id: \d+
    methods: [DELETE]

pim_enrich_attribute_create_option:
    path: /{id}/create-option/{dataLocale}
    defaults: { _controller: pim_enrich.controller.attribute:createOptionAction }
    requirements:
        id: \d+
