extensions:
    pim-attribute-edit-form-date:
        module: pim/common/simple-view
        config:
            template: pim/template/common/drop-zone

    pim-attribute-edit-form-date-validation-params:
        module: pim/common/simple-view
        parent: pim-attribute-edit-form-date
        targetZone: content
        position: 110
        config:
            template: pim/template/form/tab/section
            templateParams:
                sectionTitle: pim_enrich.form.attribute.tab.properties.validation
                dropZone: content

    pim-attribute-edit-form-date-validation-params-date-min:
        module: pim/attribute-edit-form/properties/date
        parent: pim-attribute-edit-form-date-validation-params
        targetZone: content
        position: 100
        config:
            fieldName: date_min

    pim-attribute-edit-form-date-validation-params-date-max:
        module: pim/attribute-edit-form/properties/date
        parent: pim-attribute-edit-form-date-validation-params
        targetZone: content
        position: 110
        config:
            fieldName: date_max
