extensions:
    pim-attribute-edit-form-textarea:
        module: pim/common/simple-view
        config:
            template: pim/template/common/drop-zone

    pim-attribute-edit-form-textarea-type-specific-params:
        module: pim/common/simple-view
        parent: pim-attribute-edit-form-textarea
        targetZone: content
        position: 100
        config:
            template: pim/template/form/tab/section
            templateParams:
                sectionTitle: pim_enrich.form.attribute.tab.properties.type_specific
                dropZone: content

    pim-attribute-edit-form-textarea-type-specific-params-wysiwyg-enabled:
        module: pim/attribute-edit-form/properties/boolean
        parent: pim-attribute-edit-form-textarea-type-specific-params
        targetZone: content
        position: 100
        config:
            fieldName: wysiwyg_enabled

    pim-attribute-edit-form-textarea-validation-params:
        module: pim/common/simple-view
        parent: pim-attribute-edit-form-textarea
        targetZone: content
        position: 110
        config:
            template: pim/template/form/tab/section
            templateParams:
                sectionTitle: pim_enrich.form.attribute.tab.properties.validation
                dropZone: content

    pim-attribute-edit-form-textarea-validation-params-max-characters:
        module: pim/attribute-edit-form/properties/text
        parent: pim-attribute-edit-form-textarea-validation-params
        targetZone: content
        position: 100
        config:
            fieldName: max_characters
