extensions:
    pim-attribute-edit-form-file:
        module: pim/common/simple-view
        config:
            template: pim/template/common/drop-zone

    pim-attribute-edit-form-file-validation-params:
        module: pim/common/simple-view
        parent: pim-attribute-edit-form-file
        targetZone: content
        position: 110
        config:
            template: pim/template/form/tab/section
            templateParams:
                sectionTitle: pim_enrich.form.attribute.tab.properties.validation
                dropZone: content

    pim-attribute-edit-form-file-validation-params-max-file-size:
        module: pim/attribute-edit-form/properties/text
        parent: pim-attribute-edit-form-file-validation-params
        targetZone: content
        position: 100
        config:
            fieldName: max_file_size

    pim-attribute-edit-form-file-validation-params-allowed-extensions:
        module: pim/attribute-edit-form/properties/select
        parent: pim-attribute-edit-form-file-validation-params
        targetZone: content
        position: 110
        config:
            fieldName: allowed_extensions
            choices: '%pim_catalog_file_allowed_extensions%'
            isMultiple: true
