extensions:
    pim-attribute-edit-form-metric:
        module: pim/common/simple-view
        config:
            template: pim/template/common/drop-zone

    pim-attribute-edit-form-metric-type-specific-params:
        module: pim/common/simple-view
        parent: pim-attribute-edit-form-metric
        targetZone: content
        position: 100
        config:
            template: pim/template/form/tab/section
            templateParams:
                sectionTitle: pim_enrich.form.attribute.tab.properties.type_specific
                dropZone: content

    pim-attribute-edit-form-metric-type-specific-params-metric-family:
        module: pim/attribute-edit-form/properties/metric-family
        parent: pim-attribute-edit-form-metric-type-specific-params
        targetZone: content
        position: 100
        config:
            fieldName: metric_family

    pim-attribute-edit-form-metric-type-specific-params-default-metric-unit:
        module: pim/attribute-edit-form/properties/default-metric-unit
        parent: pim-attribute-edit-form-metric-type-specific-params
        targetZone: content
        position: 110
        config:
            fieldName: default_metric_unit

    pim-attribute-edit-form-metric-validation-params:
        module: pim/common/simple-view
        parent: pim-attribute-edit-form-metric
        targetZone: content
        position: 110
        config:
            template: pim/template/form/tab/section
            templateParams:
                sectionTitle: pim_enrich.form.attribute.tab.properties.validation
                dropZone: content

    pim-attribute-edit-form-metric-validation-params-negative-allowed:
        module: pim/attribute-edit-form/properties/boolean
        parent: pim-attribute-edit-form-metric-validation-params
        targetZone: content
        position: 100
        config:
            fieldName: negative_allowed

    pim-attribute-edit-form-metric-validation-params-decimals-allowed:
        module: pim/attribute-edit-form/properties/boolean
        parent: pim-attribute-edit-form-metric-validation-params
        targetZone: content
        position: 110
        config:
            fieldName: decimals_allowed

    pim-attribute-edit-form-metric-validation-params-min-number:
        module: pim/attribute-edit-form/properties/text
        parent: pim-attribute-edit-form-metric-validation-params
        targetZone: content
        position: 120
        config:
            fieldName: min_number

    pim-attribute-edit-form-metric-validation-params-max-number:
        module: pim/attribute-edit-form/properties/text
        parent: pim-attribute-edit-form-metric-validation-params
        targetZone: content
        position: 130
        config:
            fieldName: max_number
